---
- block:
    - name: add elastic apt key
      apt_key:
        url: https://packages.elastic.co/GPG-KEY-elasticsearch

    - name: add beats apt repository
      apt_repository:
        filename: beats
        repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main

    - name: install filebeat
      apt:
        name: "{{ 'filebeat=' + filebeat_version + '*' if filebeat_version else 'filebeat' }}"
        state: present
      register: filebeat_repo_installed
      ignore_errors: "{{ filebeat_package_install_fallback|bool and filebeat_version and filebeat_version|length > 0 }}"
      notify: restart filebeat

    - set_fact:
        filebeat_install_from_repo: no
      when: filebeat_repo_installed|failed and filebeat_package_install_fallback

  when: filebeat_install_from_repo

- block:
    - name: download filebeat deb
      get_url:
        url: "{{ filebeat_artifact_baseurl }}/{{ filebeat_deb_filename }}"
        checksum: "{{ filebeat_deb_checksum|default(omit) }}"
        dest: "{{ filebeat_artficat_download_dir }}/{{ filebeat_deb_filename}}"

    - name: install filebeat deb
      apt:
        deb: "{{ filebeat_artficat_download_dir }}/{{ filebeat_deb_filename }}"
        state: present
        force: yes
      notify: restart filebeat

  when: not filebeat_install_from_repo
