---
- block:
    - name: add elastic rpm key
      rpm_key:
        key: https://packages.elastic.co/GPG-KEY-elasticsearch

    - name: add beats yum repo
      yum_repository:
        name: beats
        description: Elastic Beats Repository
        gpgkey: https://packages.elastic.co/GPG-KEY-elasticsearch
        baseurl: https://artifacts.elastic.co/packages/5.x/yum
        gpgcheck: yes

    - name: install filebeat
      yum:
        name: "{{ 'filebeat-' + filebeat_version if filebeat_version else 'filebeat' }}"
        state: present
      register: filebeat_repo_installed
      ignore_errors: "{{ filebeat_package_install_fallback|bool and filebeat_version and filebeat_version|length > 0 }}"
      notify: restart filebeat

    - set_fact:
        filebeat_install_from_repo: no
      when: filebeat_repo_installed|failed and filebeat_package_install_fallback

  when: filebeat_install_from_repo

- block:
    - name: download filebeat rpm
      get_url:
        url: "{{ filebeat_artifact_baseurl }}/{{ filebeat_rpm_filename }}"
        checksum: "{{ filebeat_rpm_checksum|default(omit) }}"
        dest: "{{ filebeat_artficat_download_dir }}/{{ filebeat_rpm_filename}}"

    - name: install filebeat rpm
      yum:
        name: "{{ filebeat_artficat_download_dir }}/{{ filebeat_rpm_filename }}"
        state: present

  when: not filebeat_install_from_repo
